/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Helper.ShareHelper;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.Locale;
import javax.swing.JFrame;

import javax.swing.JLabel;

/**
 *
 * @author HAIP
 */
public final class Mainframe extends javax.swing.JFrame {

    /**
     * Creates new form Mainframe
     */
    private int xx, xy;
    quanliphongthueForm qlpt;
    quanLiTaiKhoanForm qltk;
    quanlikhachhangForm qlkh;

    public Mainframe() {

        initComponents();
        hamchay();
        clickMenuleft();
        HoverMenuleft();
        HoverThanhTieuDe();
        displayCurrentTime();

    }
    // Tạo một phương thức không static để đóng MainFrame

    public void closeFrame() {
        this.dispose(); // Đóng MainFrame
    }

    void hamchay() {
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        keoThabangthanhtieude();

        txtTenTaiKhoan.setText("Xin chào " + ShareHelper.USER.getMotaten() + " !");
        txtQuyen.setText(ShareHelper.USER.getQuyen() ? "Quyền : Nhân Viên " : "Quyền : Quản Lí");

    }
    void keoThabangthanhtieude() {

        thanhtieudePanel.addMouseListener(new MouseAdapter() {

            public void mousePressed(MouseEvent e) {

                xx = e.getX();

                xy = e.getY();

            }

        });



        thanhtieudePanel.addMouseMotionListener(new MouseAdapter() {

            public void mouseDragged(MouseEvent e) {

                int x = e.getXOnScreen();

                int y = e.getYOnScreen();

                setLocation(x - xx, y - xy);

            }

        });

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenTaiKhoan = new javax.swing.JLabel();
        btnqlnv = new javax.swing.JLabel();
        btnqltk = new javax.swing.JLabel();
        btnqlcp = new javax.swing.JLabel();
        btnqllp = new javax.swing.JLabel();
        btnqlp = new javax.swing.JLabel();
        btnqlhd = new javax.swing.JLabel();
        btntk = new javax.swing.JLabel();
        btntp = new javax.swing.JLabel();
        btntc = new javax.swing.JLabel();
        txtQuyen = new javax.swing.JLabel();
        btnqlkh = new javax.swing.JLabel();
        panelFrame = new javax.swing.JPanel();
        thanhtieudePanel = new javax.swing.JPanel();
        txtHoatDong = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnminisize = new javax.swing.JLabel();
        btnMaxsize = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        txtcurrenttime = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adminator");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("QUẢN LÍ NHÀ TRỌ");
        jPanel2.add(jLabel1);

        txtTenTaiKhoan.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtTenTaiKhoan.setForeground(new java.awt.Color(242, 242, 242));
        txtTenTaiKhoan.setText("xin chào !");

        btnqlnv.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnqlnv.setForeground(new java.awt.Color(242, 242, 242));
        btnqlnv.setText("Quản lí Nhân Viên");

        btnqltk.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnqltk.setForeground(new java.awt.Color(242, 242, 242));
        btnqltk.setText("Quản lí tài khoản");
        btnqltk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnqltkMouseClicked(evt);
            }
        });

        btnqlcp.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnqlcp.setForeground(new java.awt.Color(242, 242, 242));
        btnqlcp.setText("Quản Lí Chi Phí");

        btnqllp.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnqllp.setForeground(new java.awt.Color(242, 242, 242));
        btnqllp.setText("Quản Lí Loại Phòng");

        btnqlp.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnqlp.setForeground(new java.awt.Color(242, 242, 242));
        btnqlp.setText("Quản Lí Phòng");

        btnqlhd.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnqlhd.setForeground(new java.awt.Color(242, 242, 242));
        btnqlhd.setText("Quản Lí Hóa Đơn ");

        btntk.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btntk.setForeground(new java.awt.Color(242, 242, 242));
        btntk.setText("Thống Kê ");

        btntp.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btntp.setForeground(new java.awt.Color(242, 242, 242));
        btntp.setText("Quản Lí Thuê Phòng");
        btntp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntpMouseClicked(evt);
            }
        });

        btntc.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btntc.setForeground(new java.awt.Color(242, 242, 242));
        btntc.setText("Trang chủ");

        txtQuyen.setForeground(new java.awt.Color(255, 255, 255));
        txtQuyen.setText("Quyền : Nhân Viên");

        btnqlkh.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnqlkh.setForeground(new java.awt.Color(242, 242, 242));
        btnqlkh.setText("Quản Lí Khách Hàng");
        btnqlkh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnqlkhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnqlnv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnqltk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnqlcp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnqllp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnqlp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnqlhd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btntk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btntp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btntc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnqlkh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTenTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btntc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnqltk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnqlnv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnqlcp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnqllp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnqlp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnqlhd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnqlkh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btntk)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        panelFrame.setBackground(new java.awt.Color(255, 255, 255));
        panelFrame.setLayout(new java.awt.BorderLayout());

        thanhtieudePanel.setLayout(new javax.swing.BoxLayout(thanhtieudePanel, javax.swing.BoxLayout.LINE_AXIS));

        txtHoatDong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHoatDong.setText("> Trang chủ");
        thanhtieudePanel.add(txtHoatDong);

        btnminisize.setBackground(new java.awt.Color(0, 0, 102));
        btnminisize.setFont(new java.awt.Font("Adobe Arabic", 1, 24)); // NOI18N
        btnminisize.setForeground(new java.awt.Color(0, 0, 102));
        btnminisize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnminisize.setText("_");
        btnminisize.setToolTipText("");
        btnminisize.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnminisize.setAlignmentY(0.1F);
        btnminisize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminisizeMouseClicked(evt);
            }
        });

        btnMaxsize.setBackground(new java.awt.Color(0, 0, 102));
        btnMaxsize.setForeground(new java.awt.Color(0, 0, 102));
        btnMaxsize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMaxsize.setText("❐");
        btnMaxsize.setToolTipText("");
        btnMaxsize.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMaxsize.setAlignmentY(0.1F);
        btnMaxsize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaxsizeMouseClicked(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(0, 0, 102));
        btnClose.setForeground(new java.awt.Color(0, 0, 102));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");
        btnClose.setToolTipText("");
        btnClose.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnClose.setAlignmentY(0.1F);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        txtcurrenttime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcurrenttime.setText("currenttime");

        jTextField1.setForeground(new java.awt.Color(0, 51, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText("  Search");
        jTextField1.setActionCommand("<Not Set>");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtcurrenttime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 487, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnminisize, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaxsize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMaxsize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnminisize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(txtcurrenttime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        thanhtieudePanel.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thanhtieudePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thanhtieudePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntpMouseClicked
        addQlpt();
    }//GEN-LAST:event_btntpMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMaxsizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaxsizeMouseClicked
        if (getExtendedState() != JFrame.MAXIMIZED_BOTH) {
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        } else {
            setSize(1300, 700);
            setExtendedState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_btnMaxsizeMouseClicked

    private void btnminisizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminisizeMouseClicked
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnminisizeMouseClicked

    private void btnqlkhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnqlkhMouseClicked
        addQLKh();
    }//GEN-LAST:event_btnqlkhMouseClicked

    private void btnqltkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnqltkMouseClicked
        addQltk();
    }//GEN-LAST:event_btnqltkMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnMaxsize;
    private javax.swing.JLabel btnminisize;
    private javax.swing.JLabel btnqlcp;
    private javax.swing.JLabel btnqlhd;
    private javax.swing.JLabel btnqlkh;
    private javax.swing.JLabel btnqllp;
    private javax.swing.JLabel btnqlnv;
    private javax.swing.JLabel btnqlp;
    private javax.swing.JLabel btnqltk;
    private javax.swing.JLabel btntc;
    private javax.swing.JLabel btntk;
    private javax.swing.JLabel btntp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelFrame;
    private javax.swing.JPanel thanhtieudePanel;
    private javax.swing.JLabel txtHoatDong;
    private javax.swing.JLabel txtQuyen;
    private javax.swing.JLabel txtTenTaiKhoan;
    private javax.swing.JLabel txtcurrenttime;
    // End of variables declaration//GEN-END:variables

    public void displayCurrentTime() {
        new Thread(() -> {
            while (true) {
                ZonedDateTime currentDateTime = ZonedDateTime.now();
                // Định dạng thời gian theo định dạng quốc gia, ngày tháng năm và giờ (tiếng Việt)
                String formattedDateTime = DateTimeFormatter.ofLocalizedDateTime(FormatStyle.FULL)
                        .withLocale(new Locale("vi", "VN"))
                        .format(currentDateTime);
                updateUITime(formattedDateTime);
                try {
                    Thread.sleep(1000); // Tạm dừng 1 giây trước khi cập nhật thời gian tiếp theo
                } catch (InterruptedException e) {
                    System.out.println(e.getMessage() + "Lỗi hàm currentTime");
                }
            }
        }).start();
    }

    void updateUITime(String time) {
        // Cập nhật thời gian hiện tại lên giao diện người dùng tại đây
        txtcurrenttime.setText("" + time);
    }

    void clickMenuleft() {
        JLabel[] labels = {btnqlcp, btnqlhd, btnqllp, btnqlnv, btnqlp, btnqltk, btntk, btntp, btntc, btnqlkh};
        for (JLabel label : labels) {
            label.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    txtHoatDong.setText("> " + label.getText() + " ");
                }
            });
        }
    }

    void HoverMenuleft() {
        JLabel[] labels = {btnqlcp, btnqlhd, btnqllp, btnqlnv, btnqlp, btnqltk, btntk, btntp, btntc, btnqlkh};
        for (JLabel label : labels) {
            label.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    // Xử lý khi chuột di chuyển vào label 
                    label.setForeground(Color.red); // Hiển thị label  như một link
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    // Xử lý khi chuột di chuyển ra khỏi label 
                    label.setForeground(Color.white); // Trở lại trạng thái ban đầu của label 
                }
            });
        }
    }
    

    void HoverThanhTieuDe() {
        JLabel[] labels = {btnClose, btnMaxsize, btnminisize};
        for (JLabel label : labels) {
            label.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    // Xử lý khi chuột di chuyển vào label 
                    label.setForeground(Color.red); // Hiển thị label  như một link
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    // Xử lý khi chuột di chuyển ra khỏi label 
                    label.setForeground(Color.blue); // Trở lại trạng thái ban đầu của label 
                }
            });
        }
    }

    void addQlpt() {

        panelFrame.removeAll();
        this.qlpt = new quanliphongthueForm();
        panelFrame.add(this.qlpt, "Center");
        panelFrame.validate();

    }

    void addQltk() {
        panelFrame.removeAll();
        this.qltk = new quanLiTaiKhoanForm();
        panelFrame.add(this.qltk, "Center");
        panelFrame.validate();

    }
    void addQLKh(){
        panelFrame.removeAll();
        this.qlkh= new quanlikhachhangForm();
         panelFrame.add(this.qlkh, "Center");
        panelFrame.validate();
    }
}
