/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.TaiKhoanDao;
import Helper.CheckValidate;
import Helper.ShareHelper;
import Model.TaiKhoan;

import javax.swing.SwingUtilities;

/**
 *
 * @author HAIP
 */
public class quanLiTaiKhoanForm extends javax.swing.JPanel {

    /**
     * Creates new form quanLiTaiKhoanForm
     */
    TaiKhoanDao tkd = new TaiKhoanDao();
    CheckValidate validate = new CheckValidate();

    public quanLiTaiKhoanForm() {
        initComponents();
        fillTaiKhoan();
    }

    void fillTaiKhoan() {
        setForm(ShareHelper.USER);
    }

    void setForm(TaiKhoan model) {
        txtUserName.setText(model.getTentk());
        txtTenThat.setText(model.getMotaten());
        txtQuyen.setText(model.getQuyen() ? " Nhân Viên" : " Quản lí");
        txtQuyen.setToolTipText(Boolean.toString(model.getQuyen()));
        txtMatk.setText(" " + model.getMatk());
    }

    boolean checkValidate() {
        boolean check = true;
        if (!validate.areAllNotEmpty(txtUserName.getText(), txtMatKhau.getText(), txtTenThat.getText(),
                txtXacNhanMkcu.getText())) {
            check = false;
            System.out.println("Vui lÒng Nhập đầy đủ !");

        } else {
            if (txtMatKhau.getText().equals(ShareHelper.USER.getMatKhau())) {
                check = true;
            } else {
                check = false;
                System.out.println("Mật Khẩu cũ không đúng , vui lòng Nhập Lại ");
            }
        }
        return check;
    }

    TaiKhoan getForm() {
        TaiKhoan tk = new TaiKhoan();

        tk.setQuyen(Boolean.valueOf(txtQuyen.getToolTipText()));
        tk.setMotaten(txtTenThat.getText());
        tk.setMatk(txtMatk.getText());
        tk.setTentk(txtUserName.getText());
        tk.setMatKhau(txtXacNhanMkcu.getText());

        return tk;
    }

    void CapNhat() {
        if (checkValidate()) {
            tkd.Update(getForm());

            Mainframe mainFrame = (Mainframe) SwingUtilities.getWindowAncestor(this); // Lấy tham chiếu đến MainFrame từ Panel
            mainFrame.closeFrame(); // Gọi phương thức đóng MainFrame
            LoginForms forms = new LoginForms();
            forms.setVisible(true); // Hiển thị form đăng nhập

        }

        fillTaiKhoan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaTksdg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtTenThat = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtQuyen = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtMatk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        btnCapNhat = new javax.swing.JButton();
        txtXacNhanMkcu = new javax.swing.JPasswordField();
        txtMatKhau = new javax.swing.JPasswordField();
        btnAnHienMatKhau = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Quyền ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txtMaTksdg.setText("Mã Tài Khoản");
        jPanel1.add(txtMaTksdg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel3.setText("Tên Thật");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setText("Mật Khẩu Cũ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel5.setText("UserName ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtUserName.setBorder(null);
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 83, 330, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 280, -1));

        txtTenThat.setBorder(null);
        jPanel1.add(txtTenThat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 330, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 280, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 330, 10));

        txtQuyen.setBorder(null);
        txtQuyen.setEnabled(false);
        jPanel1.add(txtQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 330, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 330, 10));

        txtMatk.setBorder(null);
        txtMatk.setEnabled(false);
        jPanel1.add(txtMatk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 330, 30));

        jLabel6.setText("Mật Khẩu Mới");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, -1));

        btnCapNhat.setBackground(new java.awt.Color(0, 51, 102));
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setMnemonic('C');
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jPanel1.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        txtXacNhanMkcu.setBorder(null);
        txtXacNhanMkcu.setEchoChar('\u274b');
        jPanel1.add(txtXacNhanMkcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, -1));

        txtMatKhau.setBorder(null);
        txtMatKhau.setEchoChar('\u274b');
        jPanel1.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 280, -1));

        btnAnHienMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hide.png"))); // NOI18N
        btnAnHienMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAnHienMatKhauMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnAnHienMatKhauMouseReleased(evt);
            }
        });
        jPanel1.add(btnAnHienMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        CapNhat();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnAnHienMatKhauMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnHienMatKhauMousePressed
        btnAnHienMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/show.png")));
        txtXacNhanMkcu.setEchoChar((char) 0);
    }//GEN-LAST:event_btnAnHienMatKhauMousePressed

    private void btnAnHienMatKhauMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnHienMatKhauMouseReleased
        btnAnHienMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hide.png")));
        txtXacNhanMkcu.setEchoChar('❋');
    }//GEN-LAST:event_btnAnHienMatKhauMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAnHienMatKhau;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel txtMaTksdg;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtMatk;
    private javax.swing.JTextField txtQuyen;
    private javax.swing.JTextField txtTenThat;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtXacNhanMkcu;
    // End of variables declaration//GEN-END:variables
}
