/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import DAO.PhongDao;
import Helper.CustomCrollBar;
import Model.Phong;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Rectangle;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicScrollBarUI;

/**
 *
 * @author HAIP
 */
public class quanliphongthueForm extends javax.swing.JPanel {

    /**
     * Creates new form quanliphongthueForm
     */
    CustomCrollBar ct= new CustomCrollBar();
    public quanliphongthueForm() {
        initComponents();
        fillPhong();
        //custum srollPane
        ct.custum(pannelphong1);

    }
    PhongDao pdao = new PhongDao();

    void fillPhong() {

        List<Phong> listPhong = pdao.select();
        int phongtrong = 0;

        int soPhong = listPhong.size(); // Đếm số lượng phòng từ cơ sở dữ liệu
        int soCot = 5; // Số lượng cột
        int soHang = (soPhong + soCot - 1) / soCot;

        JPanel cardPanel = new JPanel(new GridLayout(soHang, soCot, 10, 10));

        for (Phong phong : listPhong) {

            if (phong.isTrangThai()) {
                JPanel card = new JPanel(new GridLayout(2, 1, 5, 10));
                card.setBackground(Color.red);
                card.setBorder(new EmptyBorder(10, 10, 10, 10)); // Khoảng cách giữa các phần tử trong card
                // Tạo và thêm label "Tên thức ăn" vào card panel
                JLabel tenPhong = new JLabel("Phòng " + phong.getMaPhong() + " đang đặt");
                tenPhong.setFont(new Font("Arial", Font.BOLD, 13));
                card.add(tenPhong);
                // Tạo và thêm label "Giá tiền" vào card panel
                JLabel giaTienLabel = new JLabel("Giá: " + phong.getGiatien() + ".000 Đ");
                card.add(giaTienLabel);

                JLabel hinhanh = new JLabel();
                hinhanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rom1.png")));
                card.add(hinhanh);

                // Thêm card panel vào main card panel
                cardPanel.add(card);
                card.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        JOptionPane.showMessageDialog(null, "Mã phòng: " + phong.getMaPhong());
                    }
                });

            } else {
                phongtrong++;
                JPanel card = new JPanel(new GridLayout(2, 1, 5, 10));
                card.setBackground(Color.white);
                card.setBorder(new EmptyBorder(10, 10, 10, 10)); // Khoảng cách giữa các phần tử trong card
                // Tạo và thêm label "Tên thức ăn" vào card panel
                JLabel tenPhong = new JLabel("Phòng " + phong.getMaPhong() + " Trống");
                tenPhong.setFont(new Font("Arial", Font.BOLD, 13));
                card.add(tenPhong);
                // Tạo và thêm label "Giá tiền" vào card panel
                JLabel giaTienLabel = new JLabel("Giá: " + phong.getGiatien() + ".000 Đ");
                card.add(giaTienLabel);
                cardPanel.add(card);

                JLabel hinhanh = new JLabel();
                hinhanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rom2.png")));
                card.add(hinhanh);

                card.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        QuanLiDatPhong datPhong = new QuanLiDatPhong(phong.getMaPhong());
                        datPhong.setVisible(true);
                    }
                });
            }
        }
        txtTongPhonng1.setText("> Tổng số phòng :  " + Integer.toString(soPhong));
        txtTongPhonTrong.setText("> Tổng Phòng trống :" + Integer.toString(phongtrong));
        txtTongPhonnDangDat.setText("> Tổng phòng đang đặt : " + Integer.toString(soPhong - phongtrong));
        panelRooms.add(cardPanel);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPhong = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTongPhonng1 = new javax.swing.JLabel();
        txtTongPhonnDangDat = new javax.swing.JLabel();
        txtTongPhonTrong = new javax.swing.JLabel();
        btnDangList = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        btnTatCaPhong = new javax.swing.JButton();
        ccbLoc = new javax.swing.JComboBox<>();
        btnXuatPDF = new javax.swing.JButton();
        pannelphong1 = new javax.swing.JScrollPane();
        panelRooms = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        panelPhong.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        txtTongPhonng1.setText("> Tổng số phòng : ");

        txtTongPhonnDangDat.setText("> Tổng phòng đang đặt : ");

        txtTongPhonTrong.setText("> Tổng số phòng trống: ");

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setMnemonic('D');
        jButton1.setText("Dạng List");

        btnTatCaPhong.setBackground(new java.awt.Color(0, 51, 102));
        btnTatCaPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnTatCaPhong.setMnemonic('T');
        btnTatCaPhong.setText("Tất Cả Phòng");
        btnTatCaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTatCaPhongActionPerformed(evt);
            }
        });

        ccbLoc.setForeground(new java.awt.Color(255, 255, 255));
        ccbLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--  Tất Cả Phòng --", "-- Phòng Trống --", "-- Phòng đang đặt --", "-- Từ Giá Thấp đến Cao", "-- Từ Giá Cao Xuống Thấp --" }));

        btnXuatPDF.setBackground(new java.awt.Color(0, 51, 102));
        btnXuatPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatPDF.setMnemonic('D');
        btnXuatPDF.setText("Xuất PDF");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDangList)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtTongPhonng1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTongPhonnDangDat, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTongPhonTrong))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(ccbLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTatCaPhong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(btnXuatPDF, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTongPhonng1)
                        .addGap(4, 4, 4)
                        .addComponent(txtTongPhonnDangDat)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnXuatPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongPhonTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btnTatCaPhong)
                    .addComponent(ccbLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(btnDangList, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPhong.add(jPanel2, java.awt.BorderLayout.NORTH);

        pannelphong1.setBorder(null);

        panelRooms.setLayout(new java.awt.BorderLayout());
        pannelphong1.setViewportView(panelRooms);

        panelPhong.add(pannelphong1, java.awt.BorderLayout.CENTER);

        add(panelPhong, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTatCaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTatCaPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTatCaPhongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator btnDangList;
    private javax.swing.JButton btnTatCaPhong;
    private javax.swing.JButton btnXuatPDF;
    private javax.swing.JComboBox<String> ccbLoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelPhong;
    private javax.swing.JPanel panelRooms;
    private javax.swing.JScrollPane pannelphong1;
    private javax.swing.JLabel txtTongPhonTrong;
    private javax.swing.JLabel txtTongPhonnDangDat;
    private javax.swing.JLabel txtTongPhonng1;
    // End of variables declaration//GEN-END:variables

}
